os: osx
osx_image: xcode9.2

language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - wget https://github.com/cleanflight/blackbox-tools/releases/download/v0.4.3/blackbox-tools-0.4.3-macosx.tar.gz
  - tar -xvf ./blackbox-tools-0.4.3-macosx.tar.gz
  
