language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.3 # https://github.com/pypa/pip/issues/5226#issuecomment-384815600

install:
  - sudo pip install --upgrade pip # https://github.com/pypa/pip/issues/5226#issuecomment-384815600
env:
  global:
    - BLACKBOX_VERSION="0.4.3"
script:
  - python --version
  - pip --version
  - pip install PyInstaller
  - pyinstaller --version
  - wget https://github.com/cleanflight/blackbox-tools/releases/download/v$BLACKBOX_VERSION/blackbox-tools-$BLACKBOX_VERSION-macosx.tar.gz
  - tar -xvf blackbox-tools-0.4.3-macosx.tar.gz
  - PyInstaller PID-Analyzer.py -y
