os: osx
osx_image: xcode9.2

language: ruby
install:
  - brew install python

env:
  - BLACKBOX_VERSION="0.4.3"
script:
  - wget https://github.com/cleanflight/blackbox-tools/releases/download/v$BLACKBOX_VERSION/blackbox-tools-$BLACKBOX_VERSION-macosx.tar.gz
  - tar -xvf ./blackbox-tools-0.4.3-macosx.tar.gz
